services:

    mysql:
        container_name: Database
        image: mysql
        volumes:
            - 'apache-mysql:/var/lib/mysql'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
            - cave

    php-apache:
        container_name: Application
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/var/www/html/'
        ports:
            - '${APP_PORT:-80}:80'
        networks:
            - cave
        depends_on:
            - mysql

    composer:
        container_name: Composer
        image: composer
        volumes:
            - '.:/app'
        command: >
            bash -c "composer update
            && composer install"

networks:
    cave:
        driver: bridge

volumes:
    apache-mysql:
        driver: local
